name: Unittests
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'
    - name: Set up requirements
      run: python -m pip install -r src/dragonfly/requirements.txt
    - name: Run unittests
      run: python -m unittest
